### ISSUE TITLE
jeferson

### ISSUE THREAD

**Issue by jefersons2004** [brunosantoshx/serie-criando-sites-profissionais-passo-a-passo#3]
Parabéns pela iniciativa.....estou tentando aprender com suas aulas ....
 Utilizei o processo de login do primeiro tutorial mas estou tendo problemas, o mesmo usuário loga quando já está conectado, comprometendo a segurança......

Outra dificuldade que tenho é que saco muito pouco....tive algumas experiencias mal sucedida com o mysql que corrompia o banco de dados, então comecei a utilizar o postgresql e até agora se mostrou estável ....

meu objetivo é montar o site com a segurança proposta nos seus cursos com as seguinte hierarquia:

Login e cadastro (validação apenas uma conexão por vez);
nível do usuário;
paginas nivel1, nivel2, nivel3, nivel4, nivel5......
             geração de mapas online a partir de dados no servidor

vou ver se atualizo as informações de acordo com o ultimo tutorial....

**Comment by Hybeki** [comment]
Obrigado por repassar os seus conhecimentos :v :v :v:
